### ISSUE TITLE
Cannot build pg_repack with Visual studio 2010 Express

### ISSUE THREAD

**Issue by mladenuzelac** [reorg/pg_repack#28]
Hi, 

I cloned this repository and was trying to build the solution pg_repack.2010.sln
I am trying to build pg_repack on Visual studio 2010 Express for 64 bit windows.

Here is my error messages:

1>------ Build started: Project: bin.2010, Configuration: 9.0 x64 ------
2>------ Build started: Project: lib.2010, Configuration: 9.0 x64 ------
2>  pgut-be.c
2>..\lib\pgut\pgut-be.c(11): fatal error C1083: Cannot open include file: 'postgres.h': No such file or directory
2>  pgut-spi.c
2>..\lib\pgut\pgut-spi.c(10): fatal error C1083: Cannot open include file: 'postgres.h': No such file or directory
2>  repack.c
2>..\lib\repack.c(9): fatal error C1083: Cannot open include file: 'postgres.h': No such file or directory
1>  pgut-fe.c
1>c:\pg_repack\pg_repack\bin\pgut\pgut.h(13): fatal error C1083: Cannot open include file: 'c.h': No such file or directory
1>  pgut.c
1>..\bin\pgut\pgut.c(10): fatal error C1083: Cannot open include file: 'postgres_fe.h': No such file or directory
1>  pg_repack.c
1>c:\pg_repack\pg_repack\bin\pgut\pgut.h(13): fatal error C1083: Cannot open include file: 'c.h': No such file or directory

Can you guide to the solution

**Comment by drakkan** [comment]
It compiles fine with msvc 2013 against postgres 9.5 after applying this patch #111

**Comment by dvarrazzo** [comment]
I've applied #111 so I assume this will build right on window.
